/*
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import soton.cybersec.smcaas.smc.ui.internal.SmcActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmcExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmcActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmcActivator.getInstance().getInjector(SmcActivator.SOTON_CYBERSEC_SMCAAS_SMC_SMC);
	}
	
}
