/*
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import soton.cybersec.smcaas.smc.ui.internal.SmcActivator;

public class SmcUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmcActivator.getInstance().getInjector("soton.cybersec.smcaas.smc.Smc");
	}

}
