/*
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmcAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("soton/cyber/smcaas/smc/parser/antlr/internal/InternalSmc.tokens");
	}
}
