/*
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import soton.cyber.smcaas.smc.parser.antlr.internal.InternalSmcParser;
import soton.cyber.smcaas.smc.services.SmcGrammarAccess;

public class SmcParser extends AbstractAntlrParser {

	@Inject
	private SmcGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmcParser createParser(XtextTokenStream stream) {
		return new InternalSmcParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Smc";
	}

	public SmcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
