/**
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmcRuntimeModule /* implements AbstractSmcRuntimeModule  */{
}
