/**
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.smc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bloom Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link soton.cyber.smcaas.smc.smc.BloomFilter#getPre <em>Pre</em>}</li>
 *   <li>{@link soton.cyber.smcaas.smc.smc.BloomFilter#getPost <em>Post</em>}</li>
 * </ul>
 *
 * @see soton.cyber.smcaas.smc.smc.SmcPackage#getBloomFilter()
 * @model
 * @generated
 */
public interface BloomFilter extends Functions
{
  /**
   * Returns the value of the '<em><b>Pre</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pre</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre</em>' reference.
   * @see #setPre(VariableDecl)
   * @see soton.cyber.smcaas.smc.smc.SmcPackage#getBloomFilter_Pre()
   * @model
   * @generated
   */
  VariableDecl getPre();

  /**
   * Sets the value of the '{@link soton.cyber.smcaas.smc.smc.BloomFilter#getPre <em>Pre</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre</em>' reference.
   * @see #getPre()
   * @generated
   */
  void setPre(VariableDecl value);

  /**
   * Returns the value of the '<em><b>Post</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Post</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post</em>' reference.
   * @see #setPost(VariableDecl)
   * @see soton.cyber.smcaas.smc.smc.SmcPackage#getBloomFilter_Post()
   * @model
   * @generated
   */
  VariableDecl getPost();

  /**
   * Sets the value of the '{@link soton.cyber.smcaas.smc.smc.BloomFilter#getPost <em>Post</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post</em>' reference.
   * @see #getPost()
   * @generated
   */
  void setPost(VariableDecl value);

} // BloomFilter
