/**
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.smc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link soton.cyber.smcaas.smc.smc.Database#getTbl <em>Tbl</em>}</li>
 *   <li>{@link soton.cyber.smcaas.smc.smc.Database#getClm <em>Clm</em>}</li>
 * </ul>
 *
 * @see soton.cyber.smcaas.smc.smc.SmcPackage#getDatabase()
 * @model
 * @generated
 */
public interface Database extends Download
{
  /**
   * Returns the value of the '<em><b>Tbl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tbl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tbl</em>' containment reference.
   * @see #setTbl(Expression)
   * @see soton.cyber.smcaas.smc.smc.SmcPackage#getDatabase_Tbl()
   * @model containment="true"
   * @generated
   */
  Expression getTbl();

  /**
   * Sets the value of the '{@link soton.cyber.smcaas.smc.smc.Database#getTbl <em>Tbl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tbl</em>' containment reference.
   * @see #getTbl()
   * @generated
   */
  void setTbl(Expression value);

  /**
   * Returns the value of the '<em><b>Clm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Clm</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clm</em>' attribute.
   * @see #setClm(String)
   * @see soton.cyber.smcaas.smc.smc.SmcPackage#getDatabase_Clm()
   * @model
   * @generated
   */
  String getClm();

  /**
   * Sets the value of the '{@link soton.cyber.smcaas.smc.smc.Database#getClm <em>Clm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clm</em>' attribute.
   * @see #getClm()
   * @generated
   */
  void setClm(String value);

} // Database
