/**
 * generated by Xtext 2.13.0
 */
package soton.cyber.smcaas.smc.smc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see soton.cyber.smcaas.smc.smc.SmcPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
