/**
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.smc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see soton.cyber.smcaas.smc.smc.SmcPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends AbstractAssignment
{
} // Expression
