/**
 * generated by Xtext 2.13.0
 */
package soton.cyber.smcaas.smc.smc;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see soton.cyber.smcaas.smc.smc.SmcFactory
 * @model kind="package"
 * @generated
 */
public interface SmcPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smc";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.cyber.soton/smcaas/smc/Smc";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smc";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmcPackage eINSTANCE = soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl.init();

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.SmcImpl <em>Smc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.SmcImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getSmc()
   * @generated
   */
  int SMC = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMC__BLOCKS = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMC__MAIN = 1;

  /**
   * The number of structural features of the '<em>Smc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.BlockSMCImpl <em>Block SMC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.BlockSMCImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlockSMC()
   * @generated
   */
  int BLOCK_SMC = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_SMC__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_SMC__NAME = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_SMC__PARAMETERS = 2;

  /**
   * The number of structural features of the '<em>Block SMC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_SMC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.MainSMCImpl <em>Main SMC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.MainSMCImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getMainSMC()
   * @generated
   */
  int MAIN_SMC = 2;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_SMC__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Main SMC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_SMC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.CommandImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 3;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.InvocationVoidImpl <em>Invocation Void</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.InvocationVoidImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getInvocationVoid()
   * @generated
   */
  int INVOCATION_VOID = 4;

  /**
   * The feature id for the '<em><b>Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION_VOID__CALL = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Invocation Void</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION_VOID_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.PrintImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__VALUE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.WhileImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 6;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__CONDITION = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__BODY = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.IfThenElseImpl <em>If Then Else</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.IfThenElseImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getIfThenElse()
   * @generated
   */
  int IF_THEN_ELSE = 7;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE__CONDITION = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Brach</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE__THEN_BRACH = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE__ELSE_BRANCH = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Then Else</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableDeclImpl <em>Variable Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.VariableDeclImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableDecl()
   * @generated
   */
  int VARIABLE_DECL = 8;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__VISIBILITY = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__TYPE = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__ARRAY = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__NAME = COMMAND_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__EXP = COMMAND_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Variable Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableAssignmentImpl <em>Variable Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.VariableAssignmentImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableAssignment()
   * @generated
   */
  int VARIABLE_ASSIGNMENT = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT__VAR = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT__EXP = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.ExpressionImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 10;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.ListImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getList()
   * @generated
   */
  int LIST = 11;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__ARGS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.InvocationImpl <em>Invocation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.InvocationImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getInvocation()
   * @generated
   */
  int INVOCATION = 12;

  /**
   * The feature id for the '<em><b>Block Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION__BLOCK_NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION__FUNCTION = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION__ARGS = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Invocation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOCATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.BlockImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 13;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__COMMANDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.OrImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getOr()
   * @generated
   */
  int OR = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.AndImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getAnd()
   * @generated
   */
  int AND = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.EqualityImpl <em>Equality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.EqualityImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getEquality()
   * @generated
   */
  int EQUALITY = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.ComparisonImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.PlusOrMinusImpl <em>Plus Or Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.PlusOrMinusImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getPlusOrMinus()
   * @generated
   */
  int PLUS_OR_MINUS = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_OR_MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_OR_MINUS__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_OR_MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Plus Or Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_OR_MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.MulOrDivImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getMulOrDiv()
   * @generated
   */
  int MUL_OR_DIV = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mul Or Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.NotImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getNot()
   * @generated
   */
  int NOT = 20;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPRESSION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.IntLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.DoubleLiteralImpl <em>Double Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.DoubleLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getDoubleLiteral()
   * @generated
   */
  int DOUBLE_LITERAL = 22;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Double Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.BooleanLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBooleanLiteral()
   * @generated
   */
  int BOOLEAN_LITERAL = 23;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.StringLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 24;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.DateLiteralImpl <em>Date Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.DateLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getDateLiteral()
   * @generated
   */
  int DATE_LITERAL = 25;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Date Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.TimeLiteralImpl <em>Time Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.TimeLiteralImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getTimeLiteral()
   * @generated
   */
  int TIME_LITERAL = 26;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Time Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableRefImpl <em>Variable Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.impl.VariableRefImpl
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableRef()
   * @generated
   */
  int VARIABLE_REF = 27;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF__VARIABLE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.BlockType <em>Block Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.BlockType
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlockType()
   * @generated
   */
  int BLOCK_TYPE = 28;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.SecType <em>Sec Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.SecType
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getSecType()
   * @generated
   */
  int SEC_TYPE = 29;

  /**
   * The meta object id for the '{@link soton.cyber.smcaas.smc.smc.BasicType <em>Basic Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see soton.cyber.smcaas.smc.smc.BasicType
   * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBasicType()
   * @generated
   */
  int BASIC_TYPE = 30;


  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Smc <em>Smc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smc</em>'.
   * @see soton.cyber.smcaas.smc.smc.Smc
   * @generated
   */
  EClass getSmc();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.Smc#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see soton.cyber.smcaas.smc.smc.Smc#getBlocks()
   * @see #getSmc()
   * @generated
   */
  EReference getSmc_Blocks();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Smc#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see soton.cyber.smcaas.smc.smc.Smc#getMain()
   * @see #getSmc()
   * @generated
   */
  EReference getSmc_Main();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.BlockSMC <em>Block SMC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block SMC</em>'.
   * @see soton.cyber.smcaas.smc.smc.BlockSMC
   * @generated
   */
  EClass getBlockSMC();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.BlockSMC#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see soton.cyber.smcaas.smc.smc.BlockSMC#getType()
   * @see #getBlockSMC()
   * @generated
   */
  EAttribute getBlockSMC_Type();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.BlockSMC#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see soton.cyber.smcaas.smc.smc.BlockSMC#getName()
   * @see #getBlockSMC()
   * @generated
   */
  EAttribute getBlockSMC_Name();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.BlockSMC#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see soton.cyber.smcaas.smc.smc.BlockSMC#getParameters()
   * @see #getBlockSMC()
   * @generated
   */
  EReference getBlockSMC_Parameters();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.MainSMC <em>Main SMC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main SMC</em>'.
   * @see soton.cyber.smcaas.smc.smc.MainSMC
   * @generated
   */
  EClass getMainSMC();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.MainSMC#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see soton.cyber.smcaas.smc.smc.MainSMC#getCommands()
   * @see #getMainSMC()
   * @generated
   */
  EReference getMainSMC_Commands();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see soton.cyber.smcaas.smc.smc.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.InvocationVoid <em>Invocation Void</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Invocation Void</em>'.
   * @see soton.cyber.smcaas.smc.smc.InvocationVoid
   * @generated
   */
  EClass getInvocationVoid();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.InvocationVoid#getCall <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Call</em>'.
   * @see soton.cyber.smcaas.smc.smc.InvocationVoid#getCall()
   * @see #getInvocationVoid()
   * @generated
   */
  EReference getInvocationVoid_Call();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see soton.cyber.smcaas.smc.smc.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Print#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.Print#getValue()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see soton.cyber.smcaas.smc.smc.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.While#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see soton.cyber.smcaas.smc.smc.While#getCondition()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Condition();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.While#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see soton.cyber.smcaas.smc.smc.While#getBody()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Body();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.IfThenElse <em>If Then Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Then Else</em>'.
   * @see soton.cyber.smcaas.smc.smc.IfThenElse
   * @generated
   */
  EClass getIfThenElse();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.IfThenElse#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see soton.cyber.smcaas.smc.smc.IfThenElse#getCondition()
   * @see #getIfThenElse()
   * @generated
   */
  EReference getIfThenElse_Condition();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.IfThenElse#getThenBrach <em>Then Brach</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Brach</em>'.
   * @see soton.cyber.smcaas.smc.smc.IfThenElse#getThenBrach()
   * @see #getIfThenElse()
   * @generated
   */
  EReference getIfThenElse_ThenBrach();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.IfThenElse#getElseBranch <em>Else Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Branch</em>'.
   * @see soton.cyber.smcaas.smc.smc.IfThenElse#getElseBranch()
   * @see #getIfThenElse()
   * @generated
   */
  EReference getIfThenElse_ElseBranch();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.VariableDecl <em>Variable Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Decl</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl
   * @generated
   */
  EClass getVariableDecl();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.VariableDecl#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl#getVisibility()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_Visibility();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.VariableDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl#getType()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_Type();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.VariableDecl#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl#isArray()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_Array();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.VariableDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl#getName()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_Name();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.VariableDecl#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableDecl#getExp()
   * @see #getVariableDecl()
   * @generated
   */
  EReference getVariableDecl_Exp();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.VariableAssignment <em>Variable Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Assignment</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableAssignment
   * @generated
   */
  EClass getVariableAssignment();

  /**
   * Returns the meta object for the reference '{@link soton.cyber.smcaas.smc.smc.VariableAssignment#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableAssignment#getVar()
   * @see #getVariableAssignment()
   * @generated
   */
  EReference getVariableAssignment_Var();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.VariableAssignment#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableAssignment#getExp()
   * @see #getVariableAssignment()
   * @generated
   */
  EReference getVariableAssignment_Exp();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see soton.cyber.smcaas.smc.smc.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see soton.cyber.smcaas.smc.smc.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.List#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see soton.cyber.smcaas.smc.smc.List#getArgs()
   * @see #getList()
   * @generated
   */
  EReference getList_Args();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Invocation <em>Invocation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Invocation</em>'.
   * @see soton.cyber.smcaas.smc.smc.Invocation
   * @generated
   */
  EClass getInvocation();

  /**
   * Returns the meta object for the reference '{@link soton.cyber.smcaas.smc.smc.Invocation#getBlockName <em>Block Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Block Name</em>'.
   * @see soton.cyber.smcaas.smc.smc.Invocation#getBlockName()
   * @see #getInvocation()
   * @generated
   */
  EReference getInvocation_BlockName();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.Invocation#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see soton.cyber.smcaas.smc.smc.Invocation#getFunction()
   * @see #getInvocation()
   * @generated
   */
  EAttribute getInvocation_Function();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.Invocation#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see soton.cyber.smcaas.smc.smc.Invocation#getArgs()
   * @see #getInvocation()
   * @generated
   */
  EReference getInvocation_Args();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see soton.cyber.smcaas.smc.smc.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference list '{@link soton.cyber.smcaas.smc.smc.Block#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see soton.cyber.smcaas.smc.smc.Block#getCommands()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Commands();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see soton.cyber.smcaas.smc.smc.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see soton.cyber.smcaas.smc.smc.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Equality <em>Equality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality</em>'.
   * @see soton.cyber.smcaas.smc.smc.Equality
   * @generated
   */
  EClass getEquality();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Equality#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.Equality#getLeft()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Left();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.Equality#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see soton.cyber.smcaas.smc.smc.Equality#getOp()
   * @see #getEquality()
   * @generated
   */
  EAttribute getEquality_Op();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Equality#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.Equality#getRight()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see soton.cyber.smcaas.smc.smc.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Comparison#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.Comparison#getLeft()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Left();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.Comparison#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see soton.cyber.smcaas.smc.smc.Comparison#getOp()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Op();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Comparison#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.Comparison#getRight()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.PlusOrMinus <em>Plus Or Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus Or Minus</em>'.
   * @see soton.cyber.smcaas.smc.smc.PlusOrMinus
   * @generated
   */
  EClass getPlusOrMinus();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.PlusOrMinus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.PlusOrMinus#getLeft()
   * @see #getPlusOrMinus()
   * @generated
   */
  EReference getPlusOrMinus_Left();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.PlusOrMinus#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see soton.cyber.smcaas.smc.smc.PlusOrMinus#getOp()
   * @see #getPlusOrMinus()
   * @generated
   */
  EAttribute getPlusOrMinus_Op();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.PlusOrMinus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.PlusOrMinus#getRight()
   * @see #getPlusOrMinus()
   * @generated
   */
  EReference getPlusOrMinus_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.MulOrDiv <em>Mul Or Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mul Or Div</em>'.
   * @see soton.cyber.smcaas.smc.smc.MulOrDiv
   * @generated
   */
  EClass getMulOrDiv();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.MulOrDiv#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see soton.cyber.smcaas.smc.smc.MulOrDiv#getLeft()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Left();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.MulOrDiv#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see soton.cyber.smcaas.smc.smc.MulOrDiv#getOp()
   * @see #getMulOrDiv()
   * @generated
   */
  EAttribute getMulOrDiv_Op();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.MulOrDiv#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see soton.cyber.smcaas.smc.smc.MulOrDiv#getRight()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Right();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see soton.cyber.smcaas.smc.smc.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link soton.cyber.smcaas.smc.smc.Not#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see soton.cyber.smcaas.smc.smc.Not#getExpression()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expression();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.IntLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.IntLiteral#getValue()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.DoubleLiteral <em>Double Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.DoubleLiteral
   * @generated
   */
  EClass getDoubleLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.DoubleLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.DoubleLiteral#getValue()
   * @see #getDoubleLiteral()
   * @generated
   */
  EAttribute getDoubleLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.BooleanLiteral <em>Boolean Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.BooleanLiteral
   * @generated
   */
  EClass getBooleanLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.BooleanLiteral#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.BooleanLiteral#isValue()
   * @see #getBooleanLiteral()
   * @generated
   */
  EAttribute getBooleanLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.DateLiteral <em>Date Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.DateLiteral
   * @generated
   */
  EClass getDateLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.DateLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.DateLiteral#getValue()
   * @see #getDateLiteral()
   * @generated
   */
  EAttribute getDateLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.TimeLiteral <em>Time Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Literal</em>'.
   * @see soton.cyber.smcaas.smc.smc.TimeLiteral
   * @generated
   */
  EClass getTimeLiteral();

  /**
   * Returns the meta object for the attribute '{@link soton.cyber.smcaas.smc.smc.TimeLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see soton.cyber.smcaas.smc.smc.TimeLiteral#getValue()
   * @see #getTimeLiteral()
   * @generated
   */
  EAttribute getTimeLiteral_Value();

  /**
   * Returns the meta object for class '{@link soton.cyber.smcaas.smc.smc.VariableRef <em>Variable Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Ref</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableRef
   * @generated
   */
  EClass getVariableRef();

  /**
   * Returns the meta object for the reference '{@link soton.cyber.smcaas.smc.smc.VariableRef#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see soton.cyber.smcaas.smc.smc.VariableRef#getVariable()
   * @see #getVariableRef()
   * @generated
   */
  EReference getVariableRef_Variable();

  /**
   * Returns the meta object for enum '{@link soton.cyber.smcaas.smc.smc.BlockType <em>Block Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Block Type</em>'.
   * @see soton.cyber.smcaas.smc.smc.BlockType
   * @generated
   */
  EEnum getBlockType();

  /**
   * Returns the meta object for enum '{@link soton.cyber.smcaas.smc.smc.SecType <em>Sec Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sec Type</em>'.
   * @see soton.cyber.smcaas.smc.smc.SecType
   * @generated
   */
  EEnum getSecType();

  /**
   * Returns the meta object for enum '{@link soton.cyber.smcaas.smc.smc.BasicType <em>Basic Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Basic Type</em>'.
   * @see soton.cyber.smcaas.smc.smc.BasicType
   * @generated
   */
  EEnum getBasicType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmcFactory getSmcFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.SmcImpl <em>Smc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.SmcImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getSmc()
     * @generated
     */
    EClass SMC = eINSTANCE.getSmc();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMC__BLOCKS = eINSTANCE.getSmc_Blocks();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMC__MAIN = eINSTANCE.getSmc_Main();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.BlockSMCImpl <em>Block SMC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.BlockSMCImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlockSMC()
     * @generated
     */
    EClass BLOCK_SMC = eINSTANCE.getBlockSMC();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK_SMC__TYPE = eINSTANCE.getBlockSMC_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK_SMC__NAME = eINSTANCE.getBlockSMC_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK_SMC__PARAMETERS = eINSTANCE.getBlockSMC_Parameters();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.MainSMCImpl <em>Main SMC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.MainSMCImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getMainSMC()
     * @generated
     */
    EClass MAIN_SMC = eINSTANCE.getMainSMC();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_SMC__COMMANDS = eINSTANCE.getMainSMC_Commands();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.CommandImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.InvocationVoidImpl <em>Invocation Void</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.InvocationVoidImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getInvocationVoid()
     * @generated
     */
    EClass INVOCATION_VOID = eINSTANCE.getInvocationVoid();

    /**
     * The meta object literal for the '<em><b>Call</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INVOCATION_VOID__CALL = eINSTANCE.getInvocationVoid_Call();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.PrintImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__VALUE = eINSTANCE.getPrint_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.WhileImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__CONDITION = eINSTANCE.getWhile_Condition();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__BODY = eINSTANCE.getWhile_Body();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.IfThenElseImpl <em>If Then Else</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.IfThenElseImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getIfThenElse()
     * @generated
     */
    EClass IF_THEN_ELSE = eINSTANCE.getIfThenElse();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE__CONDITION = eINSTANCE.getIfThenElse_Condition();

    /**
     * The meta object literal for the '<em><b>Then Brach</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE__THEN_BRACH = eINSTANCE.getIfThenElse_ThenBrach();

    /**
     * The meta object literal for the '<em><b>Else Branch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE__ELSE_BRANCH = eINSTANCE.getIfThenElse_ElseBranch();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableDeclImpl <em>Variable Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.VariableDeclImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableDecl()
     * @generated
     */
    EClass VARIABLE_DECL = eINSTANCE.getVariableDecl();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__VISIBILITY = eINSTANCE.getVariableDecl_Visibility();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__TYPE = eINSTANCE.getVariableDecl_Type();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__ARRAY = eINSTANCE.getVariableDecl_Array();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__NAME = eINSTANCE.getVariableDecl_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECL__EXP = eINSTANCE.getVariableDecl_Exp();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableAssignmentImpl <em>Variable Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.VariableAssignmentImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableAssignment()
     * @generated
     */
    EClass VARIABLE_ASSIGNMENT = eINSTANCE.getVariableAssignment();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ASSIGNMENT__VAR = eINSTANCE.getVariableAssignment_Var();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ASSIGNMENT__EXP = eINSTANCE.getVariableAssignment_Exp();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.ExpressionImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.ListImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__ARGS = eINSTANCE.getList_Args();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.InvocationImpl <em>Invocation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.InvocationImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getInvocation()
     * @generated
     */
    EClass INVOCATION = eINSTANCE.getInvocation();

    /**
     * The meta object literal for the '<em><b>Block Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INVOCATION__BLOCK_NAME = eINSTANCE.getInvocation_BlockName();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVOCATION__FUNCTION = eINSTANCE.getInvocation_Function();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INVOCATION__ARGS = eINSTANCE.getInvocation_Args();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.BlockImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__COMMANDS = eINSTANCE.getBlock_Commands();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.OrImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.AndImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.EqualityImpl <em>Equality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.EqualityImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getEquality()
     * @generated
     */
    EClass EQUALITY = eINSTANCE.getEquality();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__LEFT = eINSTANCE.getEquality_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUALITY__OP = eINSTANCE.getEquality_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__RIGHT = eINSTANCE.getEquality_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.ComparisonImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__LEFT = eINSTANCE.getComparison_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OP = eINSTANCE.getComparison_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__RIGHT = eINSTANCE.getComparison_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.PlusOrMinusImpl <em>Plus Or Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.PlusOrMinusImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getPlusOrMinus()
     * @generated
     */
    EClass PLUS_OR_MINUS = eINSTANCE.getPlusOrMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_OR_MINUS__LEFT = eINSTANCE.getPlusOrMinus_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUS_OR_MINUS__OP = eINSTANCE.getPlusOrMinus_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_OR_MINUS__RIGHT = eINSTANCE.getPlusOrMinus_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.MulOrDivImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getMulOrDiv()
     * @generated
     */
    EClass MUL_OR_DIV = eINSTANCE.getMulOrDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__LEFT = eINSTANCE.getMulOrDiv_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MUL_OR_DIV__OP = eINSTANCE.getMulOrDiv_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__RIGHT = eINSTANCE.getMulOrDiv_Right();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.NotImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPRESSION = eINSTANCE.getNot_Expression();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.IntLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getIntLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.DoubleLiteralImpl <em>Double Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.DoubleLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getDoubleLiteral()
     * @generated
     */
    EClass DOUBLE_LITERAL = eINSTANCE.getDoubleLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE_LITERAL__VALUE = eINSTANCE.getDoubleLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.BooleanLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBooleanLiteral()
     * @generated
     */
    EClass BOOLEAN_LITERAL = eINSTANCE.getBooleanLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_LITERAL__VALUE = eINSTANCE.getBooleanLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.StringLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.DateLiteralImpl <em>Date Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.DateLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getDateLiteral()
     * @generated
     */
    EClass DATE_LITERAL = eINSTANCE.getDateLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_LITERAL__VALUE = eINSTANCE.getDateLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.TimeLiteralImpl <em>Time Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.TimeLiteralImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getTimeLiteral()
     * @generated
     */
    EClass TIME_LITERAL = eINSTANCE.getTimeLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_LITERAL__VALUE = eINSTANCE.getTimeLiteral_Value();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.impl.VariableRefImpl <em>Variable Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.impl.VariableRefImpl
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getVariableRef()
     * @generated
     */
    EClass VARIABLE_REF = eINSTANCE.getVariableRef();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_REF__VARIABLE = eINSTANCE.getVariableRef_Variable();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.BlockType <em>Block Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.BlockType
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBlockType()
     * @generated
     */
    EEnum BLOCK_TYPE = eINSTANCE.getBlockType();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.SecType <em>Sec Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.SecType
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getSecType()
     * @generated
     */
    EEnum SEC_TYPE = eINSTANCE.getSecType();

    /**
     * The meta object literal for the '{@link soton.cyber.smcaas.smc.smc.BasicType <em>Basic Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see soton.cyber.smcaas.smc.smc.BasicType
     * @see soton.cyber.smcaas.smc.smc.impl.SmcPackageImpl#getBasicType()
     * @generated
     */
    EEnum BASIC_TYPE = eINSTANCE.getBasicType();

  }

} //SmcPackage
