/**
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.ui.contentassist;

import soton.cybersec.smcaas.smc.ui.contentassist.AbstractSmcProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmcProposalProvider extends AbstractSmcProposalProvider {
}
