/**
 * generated by Xtext 2.12.0
 */
package soton.cyber.smcaas.smc.ide;

import soton.cyber.smcaas.smc.ide.AbstractSmcIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmcIdeModule extends AbstractSmcIdeModule {
}
