/**
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.validation;

import soton.cybersec.smcaas.smc.validation.AbstractSmcValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmcValidator extends AbstractSmcValidator {
}
