/*
 * generated by Xtext 2.13.0
 */
package soton.cyber.smcaas.smc.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SmcGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SmcElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Smc");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Assignment cBlocksAssignment_0 = (Assignment)cUnorderedGroup.eContents().get(0);
		private final RuleCall cBlocksBlockSMCParserRuleCall_0_0 = (RuleCall)cBlocksAssignment_0.eContents().get(0);
		private final Assignment cMainAssignment_1 = (Assignment)cUnorderedGroup.eContents().get(1);
		private final RuleCall cMainMainSMCParserRuleCall_1_0 = (RuleCall)cMainAssignment_1.eContents().get(0);
		
		//Smc:
		//	blocks+=BlockSMC* & main=MainSMC?;
		@Override public ParserRule getRule() { return rule; }
		
		//blocks+=BlockSMC* & main=MainSMC?
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//blocks+=BlockSMC*
		public Assignment getBlocksAssignment_0() { return cBlocksAssignment_0; }
		
		//BlockSMC
		public RuleCall getBlocksBlockSMCParserRuleCall_0_0() { return cBlocksBlockSMCParserRuleCall_0_0; }
		
		//main=MainSMC?
		public Assignment getMainAssignment_1() { return cMainAssignment_1; }
		
		//MainSMC
		public RuleCall getMainMainSMCParserRuleCall_1_0() { return cMainMainSMCParserRuleCall_1_0; }
	}
	public class BlockSMCElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.BlockSMC");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBlockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeBlockTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNewKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cParametersAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cParametersExpressionParserRuleCall_6_0_0 = (RuleCall)cParametersAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cParametersAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cParametersExpressionParserRuleCall_6_1_1_0 = (RuleCall)cParametersAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//BlockSMC:
		//	'block' type=BlockType name=ID '=' 'new' '(' (parameters+=Expression (',' parameters+=Expression)*)? ')' ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'block' type=BlockType name=ID '=' 'new' '(' (parameters+=Expression (',' parameters+=Expression)*)? ')' ';'
		public Group getGroup() { return cGroup; }
		
		//'block'
		public Keyword getBlockKeyword_0() { return cBlockKeyword_0; }
		
		//type=BlockType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//BlockType
		public RuleCall getTypeBlockTypeEnumRuleCall_1_0() { return cTypeBlockTypeEnumRuleCall_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//'new'
		public Keyword getNewKeyword_4() { return cNewKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//(parameters+=Expression (',' parameters+=Expression)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//parameters+=Expression
		public Assignment getParametersAssignment_6_0() { return cParametersAssignment_6_0; }
		
		//Expression
		public RuleCall getParametersExpressionParserRuleCall_6_0_0() { return cParametersExpressionParserRuleCall_6_0_0; }
		
		//(',' parameters+=Expression)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//','
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//parameters+=Expression
		public Assignment getParametersAssignment_6_1_1() { return cParametersAssignment_6_1_1; }
		
		//Expression
		public RuleCall getParametersExpressionParserRuleCall_6_1_1_0() { return cParametersExpressionParserRuleCall_6_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//';'
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }
	}
	public class MainSMCElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.MainSMC");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMainKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cMainSMCAction_1 = (Action)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCommandsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCommandsCommandParserRuleCall_3_0 = (RuleCall)cCommandsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MainSMC:
		//	'main' {MainSMC} '{'
		//	commands+=Command*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'main' {MainSMC} '{' commands+=Command* '}'
		public Group getGroup() { return cGroup; }
		
		//'main'
		public Keyword getMainKeyword_0() { return cMainKeyword_0; }
		
		//{MainSMC}
		public Action getMainSMCAction_1() { return cMainSMCAction_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//commands+=Command*
		public Assignment getCommandsAssignment_3() { return cCommandsAssignment_3; }
		
		//Command
		public RuleCall getCommandsCommandParserRuleCall_3_0() { return cCommandsCommandParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBlockParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVariableDeclParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVariableAssignmentParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cIfThenElseParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cWhileParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cPrintParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cInvocationVoidParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Command:
		//	Block | VariableDecl | VariableAssignment | IfThenElse | While | Print | InvocationVoid;
		@Override public ParserRule getRule() { return rule; }
		
		//Block | VariableDecl | VariableAssignment | IfThenElse | While | Print | InvocationVoid
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Block
		public RuleCall getBlockParserRuleCall_0() { return cBlockParserRuleCall_0; }
		
		//VariableDecl
		public RuleCall getVariableDeclParserRuleCall_1() { return cVariableDeclParserRuleCall_1; }
		
		//VariableAssignment
		public RuleCall getVariableAssignmentParserRuleCall_2() { return cVariableAssignmentParserRuleCall_2; }
		
		//IfThenElse
		public RuleCall getIfThenElseParserRuleCall_3() { return cIfThenElseParserRuleCall_3; }
		
		//While
		public RuleCall getWhileParserRuleCall_4() { return cWhileParserRuleCall_4; }
		
		//Print
		public RuleCall getPrintParserRuleCall_5() { return cPrintParserRuleCall_5; }
		
		//InvocationVoid
		public RuleCall getInvocationVoidParserRuleCall_6() { return cInvocationVoidParserRuleCall_6; }
	}
	public class InvocationVoidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.InvocationVoid");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCallAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCallInvocationParserRuleCall_0_0 = (RuleCall)cCallAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//InvocationVoid:
		//	call=Invocation ';';
		@Override public ParserRule getRule() { return rule; }
		
		//call=Invocation ';'
		public Group getGroup() { return cGroup; }
		
		//call=Invocation
		public Assignment getCallAssignment_0() { return cCallAssignment_0; }
		
		//Invocation
		public RuleCall getCallInvocationParserRuleCall_0_0() { return cCallInvocationParserRuleCall_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class BlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Block");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlockAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCommandsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCommandsCommandParserRuleCall_2_0 = (RuleCall)cCommandsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Block Command:
		//	{Block} '{' commands+=Command* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Block} '{' commands+=Command* '}'
		public Group getGroup() { return cGroup; }
		
		//{Block}
		public Action getBlockAction_0() { return cBlockAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//commands+=Command*
		public Assignment getCommandsAssignment_2() { return cCommandsAssignment_2; }
		
		//Command
		public RuleCall getCommandsCommandParserRuleCall_2_0() { return cCommandsCommandParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueExpressionParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Print:
		//	'print' '(' value=Expression ')' ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'print' '(' value=Expression ')' ';'
		public Group getGroup() { return cGroup; }
		
		//'print'
		public Keyword getPrintKeyword_0() { return cPrintKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//value=Expression
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_2_0() { return cValueExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//';'
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}
	public class WhileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.While");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhileKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionExpressionParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBodyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBodyCommandParserRuleCall_4_0 = (RuleCall)cBodyAssignment_4.eContents().get(0);
		
		//While:
		//	'while' '(' condition=Expression ')' body=Command;
		@Override public ParserRule getRule() { return rule; }
		
		//'while' '(' condition=Expression ')' body=Command
		public Group getGroup() { return cGroup; }
		
		//'while'
		public Keyword getWhileKeyword_0() { return cWhileKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//condition=Expression
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_2_0() { return cConditionExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//body=Command
		public Assignment getBodyAssignment_4() { return cBodyAssignment_4; }
		
		//Command
		public RuleCall getBodyCommandParserRuleCall_4_0() { return cBodyCommandParserRuleCall_4_0; }
	}
	public class IfThenElseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.IfThenElse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionExpressionParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cThenBrachAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cThenBrachCommandParserRuleCall_4_0 = (RuleCall)cThenBrachAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cElseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cElseBranchAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cElseBranchCommandParserRuleCall_5_1_0 = (RuleCall)cElseBranchAssignment_5_1.eContents().get(0);
		
		//IfThenElse:
		//	'if' '(' condition=Expression ')' thenBrach=Command (=> 'else' elseBranch=Command)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'if' '(' condition=Expression ')' thenBrach=Command (=> 'else' elseBranch=Command)?
		public Group getGroup() { return cGroup; }
		
		//'if'
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//condition=Expression
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_2_0() { return cConditionExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//thenBrach=Command
		public Assignment getThenBrachAssignment_4() { return cThenBrachAssignment_4; }
		
		//Command
		public RuleCall getThenBrachCommandParserRuleCall_4_0() { return cThenBrachCommandParserRuleCall_4_0; }
		
		//(=> 'else' elseBranch=Command)?
		public Group getGroup_5() { return cGroup_5; }
		
		//=> 'else'
		public Keyword getElseKeyword_5_0() { return cElseKeyword_5_0; }
		
		//elseBranch=Command
		public Assignment getElseBranchAssignment_5_1() { return cElseBranchAssignment_5_1; }
		
		//Command
		public RuleCall getElseBranchCommandParserRuleCall_5_1_0() { return cElseBranchCommandParserRuleCall_5_1_0; }
	}
	public class VariableDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.VariableDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVisibilityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVisibilitySecTypeEnumRuleCall_1_0 = (RuleCall)cVisibilityAssignment_1.eContents().get(0);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeBasicTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Assignment cArrayAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cArrayLeftSquareBracketRightSquareBracketKeyword_3_0 = (Keyword)cArrayAssignment_3.eContents().get(0);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cExpAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cExpExpressionParserRuleCall_5_1_0 = (RuleCall)cExpAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VariableDecl:
		//	'var' visibility=SecType type=BasicType array?='[]'? name=ID ('=' exp=Expression)? ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'var' visibility=SecType type=BasicType array?='[]'? name=ID ('=' exp=Expression)? ';'
		public Group getGroup() { return cGroup; }
		
		//'var'
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//visibility=SecType
		public Assignment getVisibilityAssignment_1() { return cVisibilityAssignment_1; }
		
		//SecType
		public RuleCall getVisibilitySecTypeEnumRuleCall_1_0() { return cVisibilitySecTypeEnumRuleCall_1_0; }
		
		//type=BasicType
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//BasicType
		public RuleCall getTypeBasicTypeEnumRuleCall_2_0() { return cTypeBasicTypeEnumRuleCall_2_0; }
		
		//array?='[]'?
		public Assignment getArrayAssignment_3() { return cArrayAssignment_3; }
		
		//'[]'
		public Keyword getArrayLeftSquareBracketRightSquareBracketKeyword_3_0() { return cArrayLeftSquareBracketRightSquareBracketKeyword_3_0; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//('=' exp=Expression)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_0() { return cEqualsSignKeyword_5_0; }
		
		//exp=Expression
		public Assignment getExpAssignment_5_1() { return cExpAssignment_5_1; }
		
		//Expression
		public RuleCall getExpExpressionParserRuleCall_5_1_0() { return cExpExpressionParserRuleCall_5_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class VariableAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.VariableAssignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cVarVariableDeclCrossReference_0_0 = (CrossReference)cVarAssignment_0.eContents().get(0);
		private final RuleCall cVarVariableDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cVarVariableDeclCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpExpressionParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		////enum ArrayType:
		////	EMPTY=' ' | LIST='[]' | MATRIX='[[]]'
		////;
		//VariableAssignment:
		//	var=[VariableDecl] '=' exp=Expression ';';
		@Override public ParserRule getRule() { return rule; }
		
		//var=[VariableDecl] '=' exp=Expression ';'
		public Group getGroup() { return cGroup; }
		
		//var=[VariableDecl]
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }
		
		//[VariableDecl]
		public CrossReference getVarVariableDeclCrossReference_0_0() { return cVarVariableDeclCrossReference_0_0; }
		
		//ID
		public RuleCall getVarVariableDeclIDTerminalRuleCall_0_0_1() { return cVarVariableDeclIDTerminalRuleCall_0_0_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//exp=Expression
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }
		
		//Expression
		public RuleCall getExpExpressionParserRuleCall_2_0() { return cExpExpressionParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Expression");
		private final RuleCall cOrParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression:
		//	Or;
		@Override public ParserRule getRule() { return rule; }
		
		//Or
		public RuleCall getOrParserRuleCall() { return cOrParserRuleCall; }
	}
	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cVerticalLineVerticalLineKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Or Expression:
		//	And ({Or.left=current} "||" right=And)*;
		@Override public ParserRule getRule() { return rule; }
		
		//And ({Or.left=current} "||" right=And)*
		public Group getGroup() { return cGroup; }
		
		//And
		public RuleCall getAndParserRuleCall_0() { return cAndParserRuleCall_0; }
		
		//({Or.left=current} "||" right=And)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }
		
		//"||"
		public Keyword getVerticalLineVerticalLineKeyword_1_1() { return cVerticalLineVerticalLineKeyword_1_1; }
		
		//right=And
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//And
		public RuleCall getRightAndParserRuleCall_1_2_0() { return cRightAndParserRuleCall_1_2_0; }
	}
	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualityParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAmpersandAmpersandKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightEqualityParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//And Expression:
		//	Equality ({And.left=current} "&&" right=Equality)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Equality ({And.left=current} "&&" right=Equality)*
		public Group getGroup() { return cGroup; }
		
		//Equality
		public RuleCall getEqualityParserRuleCall_0() { return cEqualityParserRuleCall_0; }
		
		//({And.left=current} "&&" right=Equality)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }
		
		//"&&"
		public Keyword getAmpersandAmpersandKeyword_1_1() { return cAmpersandAmpersandKeyword_1_1; }
		
		//right=Equality
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Equality
		public RuleCall getRightEqualityParserRuleCall_1_2_0() { return cRightEqualityParserRuleCall_1_2_0; }
	}
	public class EqualityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Equality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparisonParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cEqualityLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpEqualsSignEqualsSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpExclamationMarkEqualsSignKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightComparisonParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Equality Expression:
		//	Comparison ({Equality.left=current} op=("==" | "!=") right=Comparison)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Comparison ({Equality.left=current} op=("==" | "!=") right=Comparison)*
		public Group getGroup() { return cGroup; }
		
		//Comparison
		public RuleCall getComparisonParserRuleCall_0() { return cComparisonParserRuleCall_0; }
		
		//({Equality.left=current} op=("==" | "!=") right=Comparison)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Equality.left=current}
		public Action getEqualityLeftAction_1_0() { return cEqualityLeftAction_1_0; }
		
		//op=("==" | "!=")
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//("==" | "!=")
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//"=="
		public Keyword getOpEqualsSignEqualsSignKeyword_1_1_0_0() { return cOpEqualsSignEqualsSignKeyword_1_1_0_0; }
		
		//"!="
		public Keyword getOpExclamationMarkEqualsSignKeyword_1_1_0_1() { return cOpExclamationMarkEqualsSignKeyword_1_1_0_1; }
		
		//right=Comparison
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Comparison
		public RuleCall getRightComparisonParserRuleCall_1_2_0() { return cRightComparisonParserRuleCall_1_2_0; }
	}
	public class ComparisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Comparison");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPlusOrMinusParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cComparisonLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpGreaterThanSignEqualsSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpLessThanSignEqualsSignKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Keyword cOpGreaterThanSignKeyword_1_1_0_2 = (Keyword)cOpAlternatives_1_1_0.eContents().get(2);
		private final Keyword cOpLessThanSignKeyword_1_1_0_3 = (Keyword)cOpAlternatives_1_1_0.eContents().get(3);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPlusOrMinusParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Comparison Expression:
		//	PlusOrMinus ({Comparison.left=current} op=(">=" | "<=" | ">" | "<") right=PlusOrMinus)*;
		@Override public ParserRule getRule() { return rule; }
		
		//PlusOrMinus ({Comparison.left=current} op=(">=" | "<=" | ">" | "<") right=PlusOrMinus)*
		public Group getGroup() { return cGroup; }
		
		//PlusOrMinus
		public RuleCall getPlusOrMinusParserRuleCall_0() { return cPlusOrMinusParserRuleCall_0; }
		
		//({Comparison.left=current} op=(">=" | "<=" | ">" | "<") right=PlusOrMinus)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Comparison.left=current}
		public Action getComparisonLeftAction_1_0() { return cComparisonLeftAction_1_0; }
		
		//op=(">=" | "<=" | ">" | "<")
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//(">=" | "<=" | ">" | "<")
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//">="
		public Keyword getOpGreaterThanSignEqualsSignKeyword_1_1_0_0() { return cOpGreaterThanSignEqualsSignKeyword_1_1_0_0; }
		
		//"<="
		public Keyword getOpLessThanSignEqualsSignKeyword_1_1_0_1() { return cOpLessThanSignEqualsSignKeyword_1_1_0_1; }
		
		//">"
		public Keyword getOpGreaterThanSignKeyword_1_1_0_2() { return cOpGreaterThanSignKeyword_1_1_0_2; }
		
		//"<"
		public Keyword getOpLessThanSignKeyword_1_1_0_3() { return cOpLessThanSignKeyword_1_1_0_3; }
		
		//right=PlusOrMinus
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//PlusOrMinus
		public RuleCall getRightPlusOrMinusParserRuleCall_1_2_0() { return cRightPlusOrMinusParserRuleCall_1_2_0; }
	}
	public class PlusOrMinusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.PlusOrMinus");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMulOrDivParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cPlusOrMinusLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpPlusSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpHyphenMinusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMulOrDivParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//PlusOrMinus Expression:
		//	MulOrDiv ({PlusOrMinus.left=current} op=('+' | '-') right=MulOrDiv)*;
		@Override public ParserRule getRule() { return rule; }
		
		//MulOrDiv ({PlusOrMinus.left=current} op=('+' | '-') right=MulOrDiv)*
		public Group getGroup() { return cGroup; }
		
		//MulOrDiv
		public RuleCall getMulOrDivParserRuleCall_0() { return cMulOrDivParserRuleCall_0; }
		
		//({PlusOrMinus.left=current} op=('+' | '-') right=MulOrDiv)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{PlusOrMinus.left=current}
		public Action getPlusOrMinusLeftAction_1_0() { return cPlusOrMinusLeftAction_1_0; }
		
		//op=('+' | '-')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('+' | '-')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'+'
		public Keyword getOpPlusSignKeyword_1_1_0_0() { return cOpPlusSignKeyword_1_1_0_0; }
		
		//'-'
		public Keyword getOpHyphenMinusKeyword_1_1_0_1() { return cOpHyphenMinusKeyword_1_1_0_1; }
		
		//right=MulOrDiv
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//MulOrDiv
		public RuleCall getRightMulOrDivParserRuleCall_1_2_0() { return cRightMulOrDivParserRuleCall_1_2_0; }
	}
	public class MulOrDivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.MulOrDiv");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cMulOrDivLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpAsteriskKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpSolidusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//MulOrDiv Expression:
		//	Primary ({MulOrDiv.left=current} op=('*' | '/') right=Primary)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Primary ({MulOrDiv.left=current} op=('*' | '/') right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({MulOrDiv.left=current} op=('*' | '/') right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{MulOrDiv.left=current}
		public Action getMulOrDivLeftAction_1_0() { return cMulOrDivLeftAction_1_0; }
		
		//op=('*' | '/')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('*' | '/')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'*'
		public Keyword getOpAsteriskKeyword_1_1_0_0() { return cOpAsteriskKeyword_1_1_0_0; }
		
		//'/'
		public Keyword getOpSolidusKeyword_1_1_0_1() { return cOpSolidusKeyword_1_1_0_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cNotAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionPrimaryParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		private final RuleCall cAtomicParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Primary Expression:
		//	'(' Expression ')' | {Not} "!" expression=Primary | Atomic;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' Expression ')' | {Not} "!" expression=Primary | Atomic
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'(' Expression ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//Expression
		public RuleCall getExpressionParserRuleCall_0_1() { return cExpressionParserRuleCall_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//{Not} "!" expression=Primary
		public Group getGroup_1() { return cGroup_1; }
		
		//{Not}
		public Action getNotAction_1_0() { return cNotAction_1_0; }
		
		//"!"
		public Keyword getExclamationMarkKeyword_1_1() { return cExclamationMarkKeyword_1_1; }
		
		//expression=Primary
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }
		
		//Primary
		public RuleCall getExpressionPrimaryParserRuleCall_1_2_0() { return cExpressionPrimaryParserRuleCall_1_2_0; }
		
		//Atomic
		public RuleCall getAtomicParserRuleCall_2() { return cAtomicParserRuleCall_2; }
	}
	public class AtomicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Atomic");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cIntLiteralAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cDoubleLiteralAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueREALTerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cBooleanLiteralAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValueBOOLEANTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cStringLiteralAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cDateLiteralAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueDATETerminalRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cTimeLiteralAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueTIMETerminalRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cVariableRefAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Assignment cVariableAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cVariableVariableDeclCrossReference_6_1_0 = (CrossReference)cVariableAssignment_6_1.eContents().get(0);
		private final RuleCall cVariableVariableDeclIDTerminalRuleCall_6_1_0_1 = (RuleCall)cVariableVariableDeclCrossReference_6_1_0.eContents().get(1);
		private final RuleCall cListParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cInvocationParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Atomic Expression:
		//	{IntLiteral} value=INT
		//	| {DoubleLiteral} value=REAL
		//	| {BooleanLiteral} value=BOOLEAN
		//	| {StringLiteral} value=STRING
		//	| {DateLiteral} value=DATE
		//	| {TimeLiteral} value=TIME
		//	| {VariableRef} variable=[VariableDecl] | List
		//	| Invocation;
		@Override public ParserRule getRule() { return rule; }
		
		//{IntLiteral} value=INT | {DoubleLiteral} value=REAL | {BooleanLiteral} value=BOOLEAN | {StringLiteral} value=STRING |
		//{DateLiteral} value=DATE | {TimeLiteral} value=TIME | {VariableRef} variable=[VariableDecl] | List | Invocation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{IntLiteral} value=INT
		public Group getGroup_0() { return cGroup_0; }
		
		//{IntLiteral}
		public Action getIntLiteralAction_0_0() { return cIntLiteralAction_0_0; }
		
		//value=INT
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_1_0() { return cValueINTTerminalRuleCall_0_1_0; }
		
		//{DoubleLiteral} value=REAL
		public Group getGroup_1() { return cGroup_1; }
		
		//{DoubleLiteral}
		public Action getDoubleLiteralAction_1_0() { return cDoubleLiteralAction_1_0; }
		
		//value=REAL
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//REAL
		public RuleCall getValueREALTerminalRuleCall_1_1_0() { return cValueREALTerminalRuleCall_1_1_0; }
		
		//{BooleanLiteral} value=BOOLEAN
		public Group getGroup_2() { return cGroup_2; }
		
		//{BooleanLiteral}
		public Action getBooleanLiteralAction_2_0() { return cBooleanLiteralAction_2_0; }
		
		//value=BOOLEAN
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }
		
		//BOOLEAN
		public RuleCall getValueBOOLEANTerminalRuleCall_2_1_0() { return cValueBOOLEANTerminalRuleCall_2_1_0; }
		
		//{StringLiteral} value=STRING
		public Group getGroup_3() { return cGroup_3; }
		
		//{StringLiteral}
		public Action getStringLiteralAction_3_0() { return cStringLiteralAction_3_0; }
		
		//value=STRING
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_3_1_0() { return cValueSTRINGTerminalRuleCall_3_1_0; }
		
		//{DateLiteral} value=DATE
		public Group getGroup_4() { return cGroup_4; }
		
		//{DateLiteral}
		public Action getDateLiteralAction_4_0() { return cDateLiteralAction_4_0; }
		
		//value=DATE
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//DATE
		public RuleCall getValueDATETerminalRuleCall_4_1_0() { return cValueDATETerminalRuleCall_4_1_0; }
		
		//{TimeLiteral} value=TIME
		public Group getGroup_5() { return cGroup_5; }
		
		//{TimeLiteral}
		public Action getTimeLiteralAction_5_0() { return cTimeLiteralAction_5_0; }
		
		//value=TIME
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//TIME
		public RuleCall getValueTIMETerminalRuleCall_5_1_0() { return cValueTIMETerminalRuleCall_5_1_0; }
		
		//{VariableRef} variable=[VariableDecl]
		public Group getGroup_6() { return cGroup_6; }
		
		//{VariableRef}
		public Action getVariableRefAction_6_0() { return cVariableRefAction_6_0; }
		
		//variable=[VariableDecl]
		public Assignment getVariableAssignment_6_1() { return cVariableAssignment_6_1; }
		
		//[VariableDecl]
		public CrossReference getVariableVariableDeclCrossReference_6_1_0() { return cVariableVariableDeclCrossReference_6_1_0; }
		
		//ID
		public RuleCall getVariableVariableDeclIDTerminalRuleCall_6_1_0_1() { return cVariableVariableDeclIDTerminalRuleCall_6_1_0_1; }
		
		//List
		public RuleCall getListParserRuleCall_7() { return cListParserRuleCall_7; }
		
		//Invocation
		public RuleCall getInvocationParserRuleCall_8() { return cInvocationParserRuleCall_8; }
	}
	public class ListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.List");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cListKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cArgsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cArgsAtomicParserRuleCall_1_0_0 = (RuleCall)cArgsAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cArgsAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cArgsAtomicParserRuleCall_1_1_1_0 = (RuleCall)cArgsAssignment_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//List:
		//	'list(' (args+=Atomic (',' args+=Atomic)*) ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'list(' (args+=Atomic (',' args+=Atomic)*) ')'
		public Group getGroup() { return cGroup; }
		
		//'list('
		public Keyword getListKeyword_0() { return cListKeyword_0; }
		
		//args+=Atomic (',' args+=Atomic)*
		public Group getGroup_1() { return cGroup_1; }
		
		//args+=Atomic
		public Assignment getArgsAssignment_1_0() { return cArgsAssignment_1_0; }
		
		//Atomic
		public RuleCall getArgsAtomicParserRuleCall_1_0_0() { return cArgsAtomicParserRuleCall_1_0_0; }
		
		//(',' args+=Atomic)*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//','
		public Keyword getCommaKeyword_1_1_0() { return cCommaKeyword_1_1_0; }
		
		//args+=Atomic
		public Assignment getArgsAssignment_1_1_1() { return cArgsAssignment_1_1_1; }
		
		//Atomic
		public RuleCall getArgsAtomicParserRuleCall_1_1_1_0() { return cArgsAtomicParserRuleCall_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class InvocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.Invocation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBlockNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cBlockNameBlockSMCCrossReference_0_0 = (CrossReference)cBlockNameAssignment_0.eContents().get(0);
		private final RuleCall cBlockNameBlockSMCIDTerminalRuleCall_0_0_1 = (RuleCall)cBlockNameBlockSMCCrossReference_0_0.eContents().get(1);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFunctionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFunctionIDTerminalRuleCall_2_0 = (RuleCall)cFunctionAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cArgsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cArgsExpressionParserRuleCall_4_0_0 = (RuleCall)cArgsAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cArgsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cArgsExpressionParserRuleCall_4_1_1_0 = (RuleCall)cArgsAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Invocation:
		//	blockName=[BlockSMC] '.' function=ID '(' (args+=Expression (',' args+=Expression)*)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//blockName=[BlockSMC] '.' function=ID '(' (args+=Expression (',' args+=Expression)*)? ')'
		public Group getGroup() { return cGroup; }
		
		//blockName=[BlockSMC]
		public Assignment getBlockNameAssignment_0() { return cBlockNameAssignment_0; }
		
		//[BlockSMC]
		public CrossReference getBlockNameBlockSMCCrossReference_0_0() { return cBlockNameBlockSMCCrossReference_0_0; }
		
		//ID
		public RuleCall getBlockNameBlockSMCIDTerminalRuleCall_0_0_1() { return cBlockNameBlockSMCIDTerminalRuleCall_0_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//function=ID
		public Assignment getFunctionAssignment_2() { return cFunctionAssignment_2; }
		
		//ID
		public RuleCall getFunctionIDTerminalRuleCall_2_0() { return cFunctionIDTerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//(args+=Expression (',' args+=Expression)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//args+=Expression
		public Assignment getArgsAssignment_4_0() { return cArgsAssignment_4_0; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_4_0_0() { return cArgsExpressionParserRuleCall_4_0_0; }
		
		//(',' args+=Expression)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//','
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//args+=Expression
		public Assignment getArgsAssignment_4_1_1() { return cArgsAssignment_4_1_1; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_4_1_1_0() { return cArgsExpressionParserRuleCall_4_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	
	public class BlockTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.BlockType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINSERTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINSERTInsert_dataKeyword_0_0 = (Keyword)cINSERTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCOMPEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCOMPMath_computationKeyword_1_0 = (Keyword)cCOMPEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSEARCHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSEARCHSearchKeyword_2_0 = (Keyword)cSEARCHEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cANONYMIZATIONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cANONYMIZATIONAnonymizationKeyword_3_0 = (Keyword)cANONYMIZATIONEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cACCESSEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cACCESSAccess_controlKeyword_4_0 = (Keyword)cACCESSEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPERMISSIONEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPERMISSIONPermission_releaseKeyword_5_0 = (Keyword)cPERMISSIONEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum BlockType:
		//	INSERT='insert_data' | COMP='math_computation' | SEARCH='search' | ANONYMIZATION='anonymization' |
		//	ACCESS='access_control' | PERMISSION='permission_release';
		public EnumRule getRule() { return rule; }
		
		//INSERT='insert_data' | COMP='math_computation' | SEARCH='search' | ANONYMIZATION='anonymization' |
		//ACCESS='access_control' | PERMISSION='permission_release'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INSERT='insert_data'
		public EnumLiteralDeclaration getINSERTEnumLiteralDeclaration_0() { return cINSERTEnumLiteralDeclaration_0; }
		
		//'insert_data'
		public Keyword getINSERTInsert_dataKeyword_0_0() { return cINSERTInsert_dataKeyword_0_0; }
		
		//COMP='math_computation'
		public EnumLiteralDeclaration getCOMPEnumLiteralDeclaration_1() { return cCOMPEnumLiteralDeclaration_1; }
		
		//'math_computation'
		public Keyword getCOMPMath_computationKeyword_1_0() { return cCOMPMath_computationKeyword_1_0; }
		
		//SEARCH='search'
		public EnumLiteralDeclaration getSEARCHEnumLiteralDeclaration_2() { return cSEARCHEnumLiteralDeclaration_2; }
		
		//'search'
		public Keyword getSEARCHSearchKeyword_2_0() { return cSEARCHSearchKeyword_2_0; }
		
		//ANONYMIZATION='anonymization'
		public EnumLiteralDeclaration getANONYMIZATIONEnumLiteralDeclaration_3() { return cANONYMIZATIONEnumLiteralDeclaration_3; }
		
		//'anonymization'
		public Keyword getANONYMIZATIONAnonymizationKeyword_3_0() { return cANONYMIZATIONAnonymizationKeyword_3_0; }
		
		//ACCESS='access_control'
		public EnumLiteralDeclaration getACCESSEnumLiteralDeclaration_4() { return cACCESSEnumLiteralDeclaration_4; }
		
		//'access_control'
		public Keyword getACCESSAccess_controlKeyword_4_0() { return cACCESSAccess_controlKeyword_4_0; }
		
		//PERMISSION='permission_release'
		public EnumLiteralDeclaration getPERMISSIONEnumLiteralDeclaration_5() { return cPERMISSIONEnumLiteralDeclaration_5; }
		
		//'permission_release'
		public Keyword getPERMISSIONPermission_releaseKeyword_5_0() { return cPERMISSIONPermission_releaseKeyword_5_0; }
	}
	public class SecTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.SecType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPUBLICEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPUBLICPublicKeyword_0_0 = (Keyword)cPUBLICEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPRIVATEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPRIVATEPrivateKeyword_1_0 = (Keyword)cPRIVATEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SecType:
		//	PUBLIC='public' | PRIVATE='private';
		public EnumRule getRule() { return rule; }
		
		//PUBLIC='public' | PRIVATE='private'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PUBLIC='public'
		public EnumLiteralDeclaration getPUBLICEnumLiteralDeclaration_0() { return cPUBLICEnumLiteralDeclaration_0; }
		
		//'public'
		public Keyword getPUBLICPublicKeyword_0_0() { return cPUBLICPublicKeyword_0_0; }
		
		//PRIVATE='private'
		public EnumLiteralDeclaration getPRIVATEEnumLiteralDeclaration_1() { return cPRIVATEEnumLiteralDeclaration_1; }
		
		//'private'
		public Keyword getPRIVATEPrivateKeyword_1_0() { return cPRIVATEPrivateKeyword_1_0; }
	}
	public class BasicTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.BasicType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINTINTKeyword_0_0 = (Keyword)cINTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDOUBLEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDOUBLEDOUBLEKeyword_1_0 = (Keyword)cDOUBLEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBOOLEANBOOLEANKeyword_2_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSTRINGSTRINGKeyword_3_0 = (Keyword)cSTRINGEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTUPLEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTUPLETUPLEKeyword_4_0 = (Keyword)cTUPLEEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum BasicType:
		//	INT | DOUBLE | BOOLEAN | STRING | TUPLE;
		public EnumRule getRule() { return rule; }
		
		//INT | DOUBLE | BOOLEAN | STRING | TUPLE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public EnumLiteralDeclaration getINTEnumLiteralDeclaration_0() { return cINTEnumLiteralDeclaration_0; }
		
		//"INT"
		public Keyword getINTINTKeyword_0_0() { return cINTINTKeyword_0_0; }
		
		//DOUBLE
		public EnumLiteralDeclaration getDOUBLEEnumLiteralDeclaration_1() { return cDOUBLEEnumLiteralDeclaration_1; }
		
		//"DOUBLE"
		public Keyword getDOUBLEDOUBLEKeyword_1_0() { return cDOUBLEDOUBLEKeyword_1_0; }
		
		//BOOLEAN
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_2() { return cBOOLEANEnumLiteralDeclaration_2; }
		
		//"BOOLEAN"
		public Keyword getBOOLEANBOOLEANKeyword_2_0() { return cBOOLEANBOOLEANKeyword_2_0; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_3() { return cSTRINGEnumLiteralDeclaration_3; }
		
		//"STRING"
		public Keyword getSTRINGSTRINGKeyword_3_0() { return cSTRINGSTRINGKeyword_3_0; }
		
		//TUPLE
		public EnumLiteralDeclaration getTUPLEEnumLiteralDeclaration_4() { return cTUPLEEnumLiteralDeclaration_4; }
		
		//"TUPLE"
		public Keyword getTUPLETUPLEKeyword_4_0() { return cTUPLETUPLEKeyword_4_0; }
	}
	
	private final SmcElements pSmc;
	private final BlockSMCElements pBlockSMC;
	private final BlockTypeElements eBlockType;
	private final MainSMCElements pMainSMC;
	private final CommandElements pCommand;
	private final InvocationVoidElements pInvocationVoid;
	private final BlockElements pBlock;
	private final PrintElements pPrint;
	private final WhileElements pWhile;
	private final IfThenElseElements pIfThenElse;
	private final VariableDeclElements pVariableDecl;
	private final SecTypeElements eSecType;
	private final BasicTypeElements eBasicType;
	private final VariableAssignmentElements pVariableAssignment;
	private final ExpressionElements pExpression;
	private final OrElements pOr;
	private final AndElements pAnd;
	private final EqualityElements pEquality;
	private final ComparisonElements pComparison;
	private final PlusOrMinusElements pPlusOrMinus;
	private final MulOrDivElements pMulOrDiv;
	private final PrimaryElements pPrimary;
	private final AtomicElements pAtomic;
	private final ListElements pList;
	private final InvocationElements pInvocation;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tINT;
	private final TerminalRule tDATE;
	private final TerminalRule tTIME;
	private final TerminalRule tREAL;
	private final TerminalRule tSTRING;
	private final TerminalRule tML_COMMENT;
	private final TerminalRule tSL_COMMENT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmcGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSmc = new SmcElements();
		this.pBlockSMC = new BlockSMCElements();
		this.eBlockType = new BlockTypeElements();
		this.pMainSMC = new MainSMCElements();
		this.pCommand = new CommandElements();
		this.pInvocationVoid = new InvocationVoidElements();
		this.pBlock = new BlockElements();
		this.pPrint = new PrintElements();
		this.pWhile = new WhileElements();
		this.pIfThenElse = new IfThenElseElements();
		this.pVariableDecl = new VariableDeclElements();
		this.eSecType = new SecTypeElements();
		this.eBasicType = new BasicTypeElements();
		this.pVariableAssignment = new VariableAssignmentElements();
		this.pExpression = new ExpressionElements();
		this.pOr = new OrElements();
		this.pAnd = new AndElements();
		this.pEquality = new EqualityElements();
		this.pComparison = new ComparisonElements();
		this.pPlusOrMinus = new PlusOrMinusElements();
		this.pMulOrDiv = new MulOrDivElements();
		this.pPrimary = new PrimaryElements();
		this.pAtomic = new AtomicElements();
		this.pList = new ListElements();
		this.pInvocation = new InvocationElements();
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.BOOLEAN");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.INT");
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.DATE");
		this.tTIME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.TIME");
		this.tREAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.REAL");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.STRING");
		this.tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.ML_COMMENT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "soton.cyber.smcaas.smc.Smc.SL_COMMENT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("soton.cyber.smcaas.smc.Smc".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Smc:
	//	blocks+=BlockSMC* & main=MainSMC?;
	public SmcElements getSmcAccess() {
		return pSmc;
	}
	
	public ParserRule getSmcRule() {
		return getSmcAccess().getRule();
	}
	
	//BlockSMC:
	//	'block' type=BlockType name=ID '=' 'new' '(' (parameters+=Expression (',' parameters+=Expression)*)? ')' ';';
	public BlockSMCElements getBlockSMCAccess() {
		return pBlockSMC;
	}
	
	public ParserRule getBlockSMCRule() {
		return getBlockSMCAccess().getRule();
	}
	
	//enum BlockType:
	//	INSERT='insert_data' | COMP='math_computation' | SEARCH='search' | ANONYMIZATION='anonymization' |
	//	ACCESS='access_control' | PERMISSION='permission_release';
	public BlockTypeElements getBlockTypeAccess() {
		return eBlockType;
	}
	
	public EnumRule getBlockTypeRule() {
		return getBlockTypeAccess().getRule();
	}
	
	//MainSMC:
	//	'main' {MainSMC} '{'
	//	commands+=Command*
	//	'}';
	public MainSMCElements getMainSMCAccess() {
		return pMainSMC;
	}
	
	public ParserRule getMainSMCRule() {
		return getMainSMCAccess().getRule();
	}
	
	//Command:
	//	Block | VariableDecl | VariableAssignment | IfThenElse | While | Print | InvocationVoid;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}
	
	//InvocationVoid:
	//	call=Invocation ';';
	public InvocationVoidElements getInvocationVoidAccess() {
		return pInvocationVoid;
	}
	
	public ParserRule getInvocationVoidRule() {
		return getInvocationVoidAccess().getRule();
	}
	
	//Block Command:
	//	{Block} '{' commands+=Command* '}';
	public BlockElements getBlockAccess() {
		return pBlock;
	}
	
	public ParserRule getBlockRule() {
		return getBlockAccess().getRule();
	}
	
	//Print:
	//	'print' '(' value=Expression ')' ';';
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//While:
	//	'while' '(' condition=Expression ')' body=Command;
	public WhileElements getWhileAccess() {
		return pWhile;
	}
	
	public ParserRule getWhileRule() {
		return getWhileAccess().getRule();
	}
	
	//IfThenElse:
	//	'if' '(' condition=Expression ')' thenBrach=Command (=> 'else' elseBranch=Command)?;
	public IfThenElseElements getIfThenElseAccess() {
		return pIfThenElse;
	}
	
	public ParserRule getIfThenElseRule() {
		return getIfThenElseAccess().getRule();
	}
	
	//VariableDecl:
	//	'var' visibility=SecType type=BasicType array?='[]'? name=ID ('=' exp=Expression)? ';';
	public VariableDeclElements getVariableDeclAccess() {
		return pVariableDecl;
	}
	
	public ParserRule getVariableDeclRule() {
		return getVariableDeclAccess().getRule();
	}
	
	//enum SecType:
	//	PUBLIC='public' | PRIVATE='private';
	public SecTypeElements getSecTypeAccess() {
		return eSecType;
	}
	
	public EnumRule getSecTypeRule() {
		return getSecTypeAccess().getRule();
	}
	
	//enum BasicType:
	//	INT | DOUBLE | BOOLEAN | STRING | TUPLE;
	public BasicTypeElements getBasicTypeAccess() {
		return eBasicType;
	}
	
	public EnumRule getBasicTypeRule() {
		return getBasicTypeAccess().getRule();
	}
	
	////enum ArrayType:
	////	EMPTY=' ' | LIST='[]' | MATRIX='[[]]'
	////;
	//VariableAssignment:
	//	var=[VariableDecl] '=' exp=Expression ';';
	public VariableAssignmentElements getVariableAssignmentAccess() {
		return pVariableAssignment;
	}
	
	public ParserRule getVariableAssignmentRule() {
		return getVariableAssignmentAccess().getRule();
	}
	
	//Expression:
	//	Or;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Or Expression:
	//	And ({Or.left=current} "||" right=And)*;
	public OrElements getOrAccess() {
		return pOr;
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}
	
	//And Expression:
	//	Equality ({And.left=current} "&&" right=Equality)*;
	public AndElements getAndAccess() {
		return pAnd;
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}
	
	//Equality Expression:
	//	Comparison ({Equality.left=current} op=("==" | "!=") right=Comparison)*;
	public EqualityElements getEqualityAccess() {
		return pEquality;
	}
	
	public ParserRule getEqualityRule() {
		return getEqualityAccess().getRule();
	}
	
	//Comparison Expression:
	//	PlusOrMinus ({Comparison.left=current} op=(">=" | "<=" | ">" | "<") right=PlusOrMinus)*;
	public ComparisonElements getComparisonAccess() {
		return pComparison;
	}
	
	public ParserRule getComparisonRule() {
		return getComparisonAccess().getRule();
	}
	
	//PlusOrMinus Expression:
	//	MulOrDiv ({PlusOrMinus.left=current} op=('+' | '-') right=MulOrDiv)*;
	public PlusOrMinusElements getPlusOrMinusAccess() {
		return pPlusOrMinus;
	}
	
	public ParserRule getPlusOrMinusRule() {
		return getPlusOrMinusAccess().getRule();
	}
	
	//MulOrDiv Expression:
	//	Primary ({MulOrDiv.left=current} op=('*' | '/') right=Primary)*;
	public MulOrDivElements getMulOrDivAccess() {
		return pMulOrDiv;
	}
	
	public ParserRule getMulOrDivRule() {
		return getMulOrDivAccess().getRule();
	}
	
	//Primary Expression:
	//	'(' Expression ')' | {Not} "!" expression=Primary | Atomic;
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//Atomic Expression:
	//	{IntLiteral} value=INT
	//	| {DoubleLiteral} value=REAL
	//	| {BooleanLiteral} value=BOOLEAN
	//	| {StringLiteral} value=STRING
	//	| {DateLiteral} value=DATE
	//	| {TimeLiteral} value=TIME
	//	| {VariableRef} variable=[VariableDecl] | List
	//	| Invocation;
	public AtomicElements getAtomicAccess() {
		return pAtomic;
	}
	
	public ParserRule getAtomicRule() {
		return getAtomicAccess().getRule();
	}
	
	//List:
	//	'list(' (args+=Atomic (',' args+=Atomic)*) ')';
	public ListElements getListAccess() {
		return pList;
	}
	
	public ParserRule getListRule() {
		return getListAccess().getRule();
	}
	
	//Invocation:
	//	blockName=[BlockSMC] '.' function=ID '(' (args+=Expression (',' args+=Expression)*)? ')';
	public InvocationElements getInvocationAccess() {
		return pInvocation;
	}
	
	public ParserRule getInvocationRule() {
		return getInvocationAccess().getRule();
	}
	
	//terminal BOOLEAN returns ecore::EBoolean:
	//	'true' | 'false';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//@ Override terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//terminal DATE:
	//	INT '/' INT '/' INT;
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal TIME:
	//	INT ':' INT ':' INT;
	public TerminalRule getTIMERule() {
		return tTIME;
	}
	
	//terminal REAL returns ecore::EDouble:
	//	('+' | '-')? '0'..'9'* ('.' '0'..'9'+)?;
	public TerminalRule getREALRule() {
		return tREAL;
	}
	
	//@ Override terminal STRING:
	//	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '"' | '/'))* '"' |
	//	"'" ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | "'" | '/'))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//@ Override terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return tML_COMMENT;
	}
	
	//@ Override terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
