/**
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.smc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block SMC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link soton.cybersec.smcaas.smc.smc.BlockSMC#getType <em>Type</em>}</li>
 *   <li>{@link soton.cybersec.smcaas.smc.smc.BlockSMC#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see soton.cybersec.smcaas.smc.smc.SmcPackage#getBlockSMC()
 * @model
 * @generated
 */
public interface BlockSMC extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link soton.cybersec.smcaas.smc.smc.BlockType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see soton.cybersec.smcaas.smc.smc.BlockType
   * @see #setType(BlockType)
   * @see soton.cybersec.smcaas.smc.smc.SmcPackage#getBlockSMC_Type()
   * @model
   * @generated
   */
  BlockType getType();

  /**
   * Sets the value of the '{@link soton.cybersec.smcaas.smc.smc.BlockSMC#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see soton.cybersec.smcaas.smc.smc.BlockType
   * @see #getType()
   * @generated
   */
  void setType(BlockType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see soton.cybersec.smcaas.smc.smc.SmcPackage#getBlockSMC_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link soton.cybersec.smcaas.smc.smc.BlockSMC#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // BlockSMC
