/**
 * generated by Xtext 2.12.0
 */
package soton.cybersec.smcaas.smc.smc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link soton.cybersec.smcaas.smc.smc.DateLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see soton.cybersec.smcaas.smc.smc.SmcPackage#getDateLiteral()
 * @model
 * @generated
 */
public interface DateLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see soton.cybersec.smcaas.smc.smc.SmcPackage#getDateLiteral_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link soton.cybersec.smcaas.smc.smc.DateLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // DateLiteral
